lab_1/urls.py
from django.conf.urls import url
from .views import index
from .views import hello

#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'hello', hello, name='hello'),
]

lab_7/urls.py
from django.conf.urls import url
from .views import index, add_friend, validate_npm, delete_friend, friend_list_json, friend_list

urlpatterns = [
    url (r'^$', index, name = 'index'),
    url (r'^add-friend/$', add_friend, name = 'add-friend'),
    url (r'^validate-npm/$', validate_npm, name = 'validate-npm'),
    url (r'^delete-friend/$', delete_friend, name='delete-friend'),
    url (r'^get-friend-list/$', friend_list_json, name = 'get-friend-list'),
    url (r'^friend-list/$', friend_list, name = 'friend-list'),
]

praktikum/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from lab_1.views import index as index_lab1
import lab_1.urls as lab_1
import lab_2.urls as lab_2
import lab_2_addon.urls as lab_2_addon
from django.views.generic.base import RedirectView
import lab_3.urls as lab_3
import lab_4.urls as lab_4
import lab_5.urls as lab_5
import lab_6.urls as lab_6
import lab_7.urls as lab_7
import lab_8.urls as lab_8
import lab_9.urls as lab_9

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^lab-1/', include(lab_1,namespace='lab-1')),
    url(r'^lab-2/', include(lab_2,namespace='lab-2')),
    url(r'^lab-3/', include(lab_3,namespace='lab-3')),
    url(r'^lab-2-addon/', include(lab_2_addon, namespace='lab-2-addon')),
    url(r'^lab-4/', include(lab_4,namespace='lab-4')),
    url(r'^lab-5/', include(lab_5,namespace='lab-5')),
    url(r'^lab-6/', include(lab_6,namespace='lab-6')),
    url(r'^lab-7/', include(lab_7,namespace='lab-7')),
    url(r'^lab-8/', include(lab_8,namespace='lab-8')),
    url(r'^lab-9/', include(lab_9,namespace='lab-9')),
    url(r'^$', RedirectView.as_view(url='/lab-6/', permanent='true'), name='index')
]

lab_7/models.py
from __future__ import unicode_literals
from django.db import models

class Friend (models.Model) :
    friend_name = models.CharField(max_length=400)
    npm = models.CharField(max_length=250, unique=True)
    added_at = models.DateField(auto_now_add=True)

    def as_dict(self) :
        return {
            "friend_name" : self.friend_name,
            "npm" : self.npm,
        }

lab_7/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.views.decorators.csrf import csrf_exempt
from .models import Friend
from .api_csui_helper.csui_helper import CSUIhelper
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
import os
import json

response = {}
response['author'] = 'Kaelky'
csui_helper = CSUIhelper()

def index(request):
    mahasiswa_list = csui_helper.instance.get_mahasiswa_list()
    friend_list = Friend.objects.all()
    page = request.GET.get("page", 1)
    #membuat sebuah objek Paginator dengan per_page 13 dan mengambil data dari get_mahasiswa_list
    paginator = Paginator(mahasiswa_list, 13)
    mahasiswa_list = paginateView(paginator, page)
    html = 'lab_7/lab_7.html'
    response['mahasiswa_list'] = mahasiswa_list
    response['friend_list'] = friend_list
    return render (request, html, response)

def paginateView (paginator , page) :
    try:
        users = paginator.page(page)
    except PageNotAnInteger:
        users = paginator.page(1)
    except EmptyPage :
        users = paginator.page(paginator.num_pages)
    return users

def friend_list (request) :
    friend_list = Friend.objects.all()
    response['friend_list'] = friend_list
    html = 'lab_7/daftar_teman.html'
    return render (request, html, response)

def friend_list_json(request) :
    friends = [obj.as_dict() for obj in Friend.objects.all()]
    return JsonResponse ({"results" : friends}, content_type = 'application/json')

@csrf_exempt
def add_friend (request) :
    if request.method == 'POST' :
        name = request.POST['name']
        npm = request.POST['npm']
        daftar_teman = Friend.objects.all()
        is_already = False
        for teman in daftar_teman:
            if (npm == teman.npm and name == teman.friend_name):
                is_already = True
        if is_already:
            return JsonResponse(None)
        else :
            friend = Friend(friend_name=name , npm=npm)
            friend.save()
            return JsonResponse (friend.as_dict())

@csrf_exempt
def delete_friend (request) :
    if request.method == 'POST':
        npm = request.POST['npm']
        Friend.objects.filter (npm=npm).delete()
        return HttpResponseRedirect('/lab-7/')

@csrf_exempt
def validate_npm (request):
    nama = request.POST.get('name')
    npm = request.POST.get('npm')
    data = {
        'is_taken' : Friend.objects.filter (npm=npm).exists() and Friend.objects.filter (friend_name=nama).exists()
        }
    return JsonResponse(data)

lab_7/templates/lab_7/daftar_teman.html
{% extends "lab_7/layout/base.html" %}

{% block content %}
    <section name="friend-list">
        <div class="container">
            <div class="row">
                <div class="col-md-8 col-lg-8">
                    <h2> Fasilkom's Friend</h2>
                    <div id="friend-list" class="list-group">

                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}
{% block javascript %}
    <script>
        $(document).ready(function () {
            $.ajax({
                method: "GET",
                url: "{% url 'lab-7:get-friend-list' %}",
                success: function (response) {
                    var array = response.results
                    if (array.length === 0) {
                      $('#friend-list').append('<span class="list-group-item alert alert-danger text-center" role="alert"> Tidak ada teman di dalam daftar teman Anda</span>')
                    }
                    else {
                      for (var i = 0; i < array.length; i++) {
                        var button = '<button type="button" class="pull-right btn btn-xs btn-danger"' + 'onClick="deleteFriend(\'' + array[i].npm + '\')">' + '&times; Hapus Teman' + '</button>' + '</div>';
                        var html = '<span><div class="list-group-item clearfix">' + array[i].friend_name + '(' + array[i].npm + ')' + '</a>' + button +'</span>';
                        $('#friend-list').append(html)
                      }
                    }
                },
                error: function(error){
                    alert("Tidak ada teman di daftar teman Anda")
                }
            });
        });

        var deleteFriend = function(npm_mahasiswa){
          $.ajax({
            method : "POST",
            url : "{% url "lab-7:delete-friend" %}",
            data : {npm:npm_mahasiswa}
          });
          window.open('../friend-list/', '_self')
        }
    </script>
{% endblock %}

lab_7/templates/lab_7/lab_7.html
{% extends "lab_7/layout/base.html" %}
{% block content %}
<section name="mahasiswa-list" id="mahasiswa-list">
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-lg-8">
                <h2> Mahasiswa Fasilkom </h2>
                <div class="list-group">
                    {% if mahasiswa_list %}
                        {% for mahasiswa in mahasiswa_list %}
                            <a class="list-group-item clearfix">
                                {{ mahasiswa.nama }}  ({{ mahasiswa.npm }})
                            <span class="pull-right">
                              <span class="btn btn-xs btn-primary" onClick="addFriend('{{ mahasiswa.nama }}', '{{ mahasiswa.npm }}')">
                                Tambahkan sebagai teman
                              </span>
                            </span>
                            </a>
                        {% endfor %}
                    {% else %}
                        <div class="alert alert-danger text-center">
                            <strong>Opps!</strong> Tidak ada mahasiswa
                        </div>
                    {% endif %}

                        {% if mahasiswa_list.has_other_pages %}
                          <ul class="pagination">
                            {% if mahasiswa_list.has_previous %}
                              <li><a href="?page={{mahasiswa_list.previous_page_number}}">&laquo;</a></li>
                            {% else %}
                              <li class="disabled"><span>&laquo;</span></li>
                            {% endif %}
                            {% for i in mahasiswa_list.paginator.page_range %}
                              {% if mahasiswa_list.number == i %}
                                <li class="active"><span>{{i}} <span class="sr-only">(current)</span></span></li>
                              {% else %}
                                <li><a href="?page={{i}}">{{i}}</a></li>
                              {% endif %}
                            {% endfor %}
                            {% if mahasiswa_list.has_next %}
                              <li><a href="?page={{mahasiswa_list.next_page_number}}">&raquo;</a></li>
                            {% else %}
                              <li class="disabled"><span>&raquo;</span></li>
                            {% endif %}
                          </ul>
                        {% endif %}
                </div>
            </div>
            <div class="col-lg-4">
                <h2> Daftar Teman </h2>
                <div class="list-group" id="friend-list">
                    {% if friend_list %}
                        {% for teman in friend_list %}
                            <a class="list-group-item clearfix">
                                {{ teman.friend_name }} ({{ teman.npm }})
                            </a>
                        {% endfor %}
                    {% else %}
                        <div class="alert alert-danger text-center">
                            <strong>Opps!</strong> Tidak ada teman
                        </div>
                    {% endif %}
                </div>
                <form id="add-friend" action="#">
                    {% csrf_token %}
                    <label for="field_npm">NPM</label>
                    <input id="field_npm" type="text" name="npm" class="form-control"/>
                    <label for="field_name">Nama</label>
                    <input id="field_name" type="text" name="name" class="form-control"/>
                    <button type="submit" onclick="validateNPM()">Tambahkan sebagai teman</button>
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock %}

{% block javascript %}
<script>
  var addFriend = function (nama, npm){
    $.ajax({
      method : "POST",
      url : "{% url "lab-7:add-friend" %}",
      data : { name: nama, npm: npm },
      success : function (friend) {
        html = '<a class="list-group-item clearfix">' + friend.friend_name + ' (' + friend.npm + ') ' + '</a>';
        $("#friend-list").append(html)
      },
      error : function (error) {
        alert("Mahasiswa tersebut sudah terdaftar sebagai teman")
      }
    });
  };

  var validateNPM = function(){
    var nama = $('#field_name').val()
    var npm = $('#field_npm').val()
    $.ajax({
      method : "POST",
      url : "{% url "lab-7:validate-npm" %}",
      data : {name: nama, npm: npm},
      success : function (bool){
        var results = bool.is_taken
        if (results) {
          alert("Mahasiswa sudah terdaftar di daftar teman Anda")
        }
        else {
          addFriend(nama, npm)
        }
      },
      error : function (error){
        alert("Mahasiswa sudah terdaftar di daftar teman Anda")
      }
    })
  };
</script>

{% endblock %}